### ISSUE TITLE
AT::Resource#fetch should give a better error

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#108]
Currently you'll get:
```
TypeError: no implicit conversion of RDF::Node into String
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/open-uri.rb:36:in `open'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/2.1.0/open-uri.rb:36:in `open'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/util/file.rb:155:in `open_file'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/reader.rb:136:in `open'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/mutable.rb:43:in `load'
	from /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:228:in `fetch'
```

**Comment by no-reply** [comment]
per discussion in #projecthydra:

> 1:13 PM jcoyne> tjohnson: okay, is that an RDF.rb bug?
1:14 PM jcoyne> seems like AT shouldn't have to handle this.
1:14 PM tjohnson> i don't think it's a bug at all
1:14 PM tjohnson> you call fetch on a thing that's not fetchable, you should get an error, right?
1:14 PM tjohnson> but we're not giving useful info about that
1:14 PM jcoyne> yea, but a better error than that.
1:14 PM tjohnson> :+1:
