### ISSUE TITLE
calling Term#as_json causes a slow query.

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#109]
This query is run:
```
CONSTRUCT { ?s ?p ?o . } WHERE { ?s ?p ?o . }
```

```
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/sparql-client-1.1.3.1/lib/sparql/client/query.rb:296:in `each_statement'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/bundler/gems/rdf-marmotta-0f51cb3a192e/lib/rdf/marmotta.rb:49:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:149:in `grep'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:149:in `query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `block in enum_for'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/enumerable.rb:156:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/enumerable.rb:156:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/enumerable.rb:156:in `each_statement'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/writable.rb:129:in `insert_statements'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/writable.rb:32:in `<<'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/mutable.rb:71:in `<<'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:264:in `reload'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:80:in `initialize'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:53:in `new'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/resource.rb:53:in `from_uri'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:174:in `make_node'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:158:in `convert_object'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:32:in `block in result'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `<<'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `block (2 levels) in enum_for'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:341:in `call'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:341:in `block (4 levels) in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:339:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:339:in `block (3 levels) in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:336:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:336:in `block (2 levels) in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:333:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:333:in `block in query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:330:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/repository.rb:330:in `query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:85:in `query'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/model/graph.rb:270:in `query_pattern'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/rdf-1.1.9/lib/rdf/mixin/queryable.rb:301:in `block in enum_for'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:31:in `each'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:31:in `each_with_object'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:31:in `result'
     # /Users/justin/.rbenv/versions/2.1.5/lib/ruby/gems/2.1.0/gems/active-triples-0.6.1/lib/active_triples/term.rb:9:in `as_json'
```

**Comment by jcoyne** [comment]
Moving this to rdf-marmotta

**Comment by no-reply** [comment]
This is an issue with a particular `RDF::Repository` implementation.  Any queries are run at a lower level of abstraction that `ActiveTriples`.  Closing this.
