### ISSUE TITLE
Initialize without a URI causes a reload

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#110]
```
active-triples (0.6.1) lib/active_triples/resource.rb:264:in `reload'
active-triples (0.6.1) lib/active_triples/resource.rb:80:in `initialize'
```

Caused by calling `new` on a ActiveTriples::Resource. This is a problem if you use a repostitory because it ends up creating a query like: `CONSTRUCT { _:g70352850510440 ?p ?o . } WHERE { _:g70352850510440 ?p ?o . }`

**Comment by jcoyne** [comment]
Closed. Same as #87
