### ISSUE TITLE
regression in behavior of valid?

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#145]
With ActiveTriples 0.6 valid? was provided by ActiveModel::Validations, in 0.7 it's provided by RDF::Mixin::Enumerable

**Comment by no-reply** [comment]
Can you provide some examples of behavior that has regressed?  I believe we've taken care to ensure that validations work in a way that's compatible with both `ActiveModel` and RDF.rb.

See, e.g.: https://github.com/ActiveTriples/ActiveTriples/commit/320861703b6ed7e8a744c7ab1ef54a840c816271

**Comment by jcoyne** [comment]
If you run the test suite for https://github.com/no-reply/linked_vocabs with AT 0.7 you get:

```
Failures:

  1) LinkedVocabs::Controlled uris is invalid if the uri is not in the vocabulary
     Failure/Error: expect(d).not_to be_valid
       expected `#<DummyAuthority:0x3ff94fdf3f1c(#<DummyAuthority:0x007ff29fbe7e38>)>.valid?` to return false, got true
     # ./spec/controlled_spec.rb:147:in `block (3 levels) in <top (required)>'

  2) LinkedVocabs::Controlled uris is invalid if the uri string is not in the vocabulary
     Failure/Error: expect(d).not_to be_valid
       expected `#<DummyAuthority:0x3ff94fe0bcfc(#<DummyAuthority:0x007ff29fc179f8>)>.valid?` to return false, got true
     # ./spec/controlled_spec.rb:151:in `block (3 levels) in <top (required)>'

  3) LinkedVocabs::Controlled uris is invalid if the uri string is not in the strict vocabulary but has vocab prefix
     Failure/Error: expect(d).not_to be_valid
       expected `#<DummyAuthority:0x3ff94fe23cd0(#<DummyAuthority:0x007ff29fc479a0>)>.valid?` to return false, got true
     # ./spec/controlled_spec.rb:155:in `block (3 levels) in <top (required)>'

  4) LinkedVocabs::Controlled uris should raise an error if the uri string just the prefix
     Failure/Error: expect(d).not_to be_valid
       expected `#<DummyAuthority:0x3ff94fe3bf38(#<DummyAuthority:0x007ff29fc77e70>)>.valid?` to return false, got true
     # ./spec/controlled_spec.rb:159:in `block (3 levels) in <top (required)>'

  5) LinkedVocabs::Validators::PropertyValidator with value in vocabulary is invalid with other invalid values
     Failure/Error: expect(subject).not_to be_valid
       expected `#<DummyResource:0x3ff94fe9f4d4(#<DummyResource:0x007ff29fd3e9a8>)>.valid?` to return false, got true
     # ./spec/property_validator_spec.rb:37:in `block (3 levels) in <top (required)>'

  6) LinkedVocabs::Validators::PropertyValidator with value out of vocabulary is invalid
     Failure/Error: expect(subject).not_to be_valid
       expected `#<DummyResource:0x3ff94de168ac(#<DummyResource:0x007ff29bc2d158>)>.valid?` to return false, got true
     # ./spec/property_validator_spec.rb:46:in `block (3 levels) in <top (required)>'

  7) LinkedVocabs::Validators::PropertyValidator with value of wrong class is invalid
     Failure/Error: expect(subject).not_to be_valid
       expected `#<DummyResource:0x3ff950ca1244(#<DummyResource:0x007ff2a1942488>)>.valid?` to return false, got true
     # ./spec/property_validator_spec.rb:61:in `block (3 levels) in <top (required)>'

  8) LinkedVocabs::Validators::PropertyValidator with literal value is invalid
     Failure/Error: expect(subject).not_to be_valid
       expected `#<DummyResource:0x3ff94dddedf8(#<DummyResource:0x007ff29bbbdbf0>)>.valid?` to return false, got true
     # ./spec/property_validator_spec.rb:70:in `block (3 levels) in <top (required)>'

Finished in 1.43 seconds (files took 0.97127 seconds to load)
36 examples, 8 failures

Failed examples:

rspec ./spec/controlled_spec.rb:145 # LinkedVocabs::Controlled uris is invalid if the uri is not in the vocabulary
rspec ./spec/controlled_spec.rb:149 # LinkedVocabs::Controlled uris is invalid if the uri string is not in the vocabulary
rspec ./spec/controlled_spec.rb:153 # LinkedVocabs::Controlled uris is invalid if the uri string is not in the strict vocabulary but has vocab prefix
rspec ./spec/controlled_spec.rb:157 # LinkedVocabs::Controlled uris should raise an error if the uri string just the prefix
rspec ./spec/property_validator_spec.rb:35 # LinkedVocabs::Validators::PropertyValidator with value in vocabulary is invalid with other invalid values
rspec ./spec/property_validator_spec.rb:45 # LinkedVocabs::Validators::PropertyValidator with value out of vocabulary is invalid
rspec ./spec/property_validator_spec.rb:60 # LinkedVocabs::Validators::PropertyValidator with value of wrong class is invalid
rspec ./spec/property_validator_spec.rb:69 # LinkedVocabs::Validators::PropertyValidator with literal value is invalid
```

It does pass with 0.8, but AF isn't compatible with that version yet.
