### ISSUE TITLE
Setting a value is calling persist! in AF::Datastream:

### ISSUE THREAD

**Issue by jcoyne** [ActiveTriples/ActiveTriples#27]
This causes a remote save, just by updating one property.

Persist called from here: https://github.com/no-reply/ActiveTriples/blob/master/lib/active_triples/term.rb#L124

```
     # ./lib/active_fedora/rdf/object_resource.rb:12:in `persist!'
     # /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/active-triples-0.2.2/lib/active_triples/term.rb:124:in `add_child_node'
     # /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/active-triples-0.2.2/lib/active_triples/term.rb:107:in `set_value'
     # /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/active-triples-0.2.2/lib/active_triples/term.rb:26:in `block in set'
     # /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/active-triples-0.2.2/lib/active_triples/term.rb:25:in `each'
     # /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/active-triples-0.2.2/lib/active_triples/term.rb:25:in `set'
     # /Users/justin/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/active-triples-0.2.2/lib/active_triples/resource.rb:276:in `set_value'
     # ./lib/active_fedora/rdf/rdf_datastream.rb:8:in `set_value'
```

**Comment by no-reply** [comment]
ping @jcoyne.

If this isn't still a live issue. I'd like to close it.  Otherwise, I think I need more info.
